project/shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from cart.views import (CategoryLV,CategoryDV,ProductDV,CategoryCreate,ProductLV,register,profile,CategoryUpdate,CategoryDelete,ProductCreate,
                        ProductDelete,ProductUpdate,add_to_cart,remove_from_cart,removesingle,mycart,delivery,payment,updateprofile,
                        UserList,OrderLV,OrderDV,OrderUpdate,
                        OrderDelete,OrderitemDV,OrderitemUpdate,
                        OrderitemDelete,UserDetail,UserUpdate,UserDelete)
from cart import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',register,name='register'),
    path('',ProductLV.as_view(),name='productlist'),
    path('login/',auth_views.LoginView.as_view(template_name='cart/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='cart/logout.html'),name='logout'),
    path('profile/',profile,name='profile'),
    path('delivery/',delivery,name='delivery'),
    path('payment/',payment,name='payment'),
    path('users/',UserList.as_view(),name='userlist'),
    path('users/<pk>/',UserDetail.as_view(),name='userdetail'),
    path('users/<pk>/update/',UserUpdate.as_view(),name='userupdate'),
    path('users/<pk>/delete/',UserDelete,name='userdelete'),








    path('orders/',OrderLV.as_view(),name='orderlist'),
    path('orders/<pk>/',OrderDV.as_view(),name='orderdetail'),
    path('orders/<pk>/update/',OrderUpdate.as_view(),name='orderupdate'),
    path('orders/<pk>/delete/',OrderDelete.as_view(),name='orderdelete'),

    path('orderitem/<pk>/',OrderitemDV.as_view(),name='orderitemdetail'),
    path('orderitem/<pk>/update/',OrderitemUpdate.as_view(),name='orderitemupdate'),
    path('orderitem/<pk>/delete/',OrderitemDelete.as_view(),name='orderitemdelete'),










    path('categories/',CategoryLV.as_view(),name='categorylist'),
    path('categories/add/',CategoryCreate.as_view(),name='categorycreate'),
    path('categories/<pk>/',CategoryDV.as_view(),name='categorydetail'),
    path('categories/<pk>/update/',CategoryUpdate.as_view(),name='categoryupdate'),
    path('categories/<pk>/delete/',CategoryDelete.as_view(),name='categorydelete'),
    path('product/addp/',ProductCreate.as_view(),name='productcreate'),
    path('product/<pk>/',ProductDV.as_view(),name='productdetail'),
    path('product/<pk>/updatep/',ProductUpdate.as_view(),name='productupdate'),
    path('product/<pk>/deletep/',ProductDelete.as_view(),name='productdelete'),
    path('mycart/',mycart,name='mycart'),
    path('updateprofile/',updateprofile,name='updateprofile'),

    path('<pk>/addtocart/',add_to_cart,name='addtocart'),
    path('<pk>/removefromcart/',remove_from_cart,name='removefromcart'),
    path('<pk>/removesingle/',removesingle,name='removesingle'),









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

project/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('categorylist')

class Product(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(default="defaultpic.png",upload_to='products')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.FloatField()
    seller = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('productdetail',kwargs={'pk':self.pk})




# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="defaultprofile.png",upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args,**kwargs)
        img = Image.open(self.image.path)

        if img.height>200 or img.width>200:
            output_size = (200,200)
            img.thumbnail(output_size)
            img.save(self.image.path)

    @receiver(post_save,sender=User)
    def create_profile(sender,instance,created,**kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save,sender=User)
    def save_profile(sender,instance,**kwargs):
        instance.profile.save()

class Orderitem(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def totalprice(self):
        return self.product.price*self.quantity

    def __str__(self):
        return '{0}-{1}'.format(self.customer,self.product.title)

    def get_absolute_url(self):
        return reverse('orderlist')


class Order(models.Model):
    customer = models.ForeignKey(User,on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default = False)
    items = models.ManyToManyField(Orderitem)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        total=0
        for order_item in self.items.all():
            total+=order_item.totalprice()
        return total

    def get_absolute_url(self):
        return reverse('orderlist')

project/cart/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model=User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class Delivery(forms.Form):
    name = forms.CharField(max_length=200)
    mobile = forms.IntegerField()
    pincode = forms.IntegerField()
    city=forms.CharField(max_length=200)
    state=forms.CharField(max_length=200)
    houseno=forms.IntegerField()
    housename=forms.CharField(max_length=200)
    street=forms.CharField(max_length=100)
options=[('UPI','UPI'),
          ('Debit Card','Debit Card'),
          ('Credit Card','Credit Card'),
          ('Net Banking','Net Banking') ]

class Payment(forms.Form):
    option=forms.ChoiceField(choices=options,widget=forms.RadioSelect())
    name = forms.CharField(max_length=200)
    cardNo=forms.IntegerField()
    cvv=forms.IntegerField(widget=forms.PasswordInput)

project/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm,Delivery,Payment
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
from .models import Category,Product,Profile,Orderitem,Order
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin



# Create your views here.
class UserList(LoginRequiredMixin,UserPassesTestMixin,ListView):
    model = User
    fields = ['username','email']
    template_name="cart/user_list.html"

    def test_func(self):
        return self.request.user.is_superuser


class UserDetail(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = User
    template_name="cart/user_detail.html"
    def test_func(self):
        return self.request.user.is_superuser

class UserUpdate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model = User
    fields=['username','email']
    template_name="cart/user_update.html"
    success_message="User is updated"
    def test_func(self):
        return self.request.user.is_superuser





@user_passes_test(lambda u: u.is_superuser)
def UserDelete(request,pk):
    user = User.objects.filter(id=pk)
    if user.exists():
        user.delete()
        messages.success(request,'User is deleted')
    else:
        messages.info(request,'User not found')
    return redirect(reverse('userlist'))

class ProductLV(LoginRequiredMixin,ListView):
    model = Product
    ordering = ['title']

class CategoryLV(LoginRequiredMixin,ListView):
    model = Category
    ordering = ['name']

class CategoryDV(LoginRequiredMixin,DetailView):
    model = Category


class ProductDV(DetailView):
    model = Product



class CategoryCreate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,CreateView):
    model = Category
    fields=['name']
    success_message="Category created"

    def test_func(self):
        return self.request.user.is_superuser

class CategoryUpdate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model = Category
    fields = ['name']
    success_message="Category updated"


    def test_func(self):
        return self.request.user.is_superuser


class CategoryDelete(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,DeleteView):
    model = Category
    success_message="Category deleted"
    success_url = '/categories/'
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(CategoryDelete, self).delete(request, *args, **kwargs)



    def test_func(self):
        return self.request.user.is_superuser




class ProductCreate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,CreateView):
    model = Product
    fields = '__all__'
    success_message="Product created"

    def test_func(self):
        return self.request.user.is_superuser

class ProductUpdate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model = Product
    fields = '__all__'
    success_message="Product updated"


    def test_func(self):
        return self.request.user.is_superuser

class ProductDelete(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,DeleteView):
    model = Product
    success_url = '/categories/'
    success_message="Product deleted"
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ProductDelete, self).delete(request, *args, **kwargs)



    def test_func(self):
        return self.request.user.is_superuser







class OrderLV(LoginRequiredMixin,UserPassesTestMixin,ListView):
    model = Order
    ordering = ['customer']
    def test_func(self):
        return self.request.user.is_superuser

class OrderDV(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    model = Order
    def test_func(self):
        return self.request.user.is_superuser

class OrderUpdate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model = Order
    fields = '__all__'
    success_message="Order updated"


    def test_func(self):
        return self.request.user.is_superuser


class OrderDelete(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,DeleteView):
    model = Order
    success_url='/orders/'
    success_message="Order deleted"
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(OrderDelete, self).delete(request, *args, **kwargs)



    def test_func(self):
        return self.request.user.is_superuser






class OrderitemDV(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,DetailView):
    model = Orderitem
    def test_func(self):
        return self.request.user.is_superuser

class OrderitemUpdate(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,UpdateView):
    model = Orderitem
    fields = '__all__'
    success_message="Orderitem updated"


    def test_func(self):
        return self.request.user.is_superuser

class OrderitemDelete(LoginRequiredMixin,UserPassesTestMixin,SuccessMessageMixin,DeleteView):
    model = Orderitem
    success_url='/orders/'
    success_message="Orderitem deleted"


    def test_func(self):
        return self.request.user.is_superuser
    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(OrderitemDelete, self).delete(request, *args, **kwargs)














def register(request):
    if request.method=='POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
             form.save()
             username = form.cleaned_data.get('username')
             messages.success(request,f' Account created for {username}!')
             return redirect('login')
    else:
        form=UserRegisterForm()
    return render(request,'cart/register.html',{'form':form})


@login_required
def profile(request):
    user_profile = User.objects.filter(username=request.user.username)[0]
    myorders =Order.objects.filter(is_ordered=True,customer=user_profile)


    if request.method=='POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES,instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account is updated!')
            return redirect('profile')
    else:
        u_form=UserUpdateForm(instance=request.user)
        p_form=ProfileUpdateForm(instance=request.user.profile)
    context = {'u_form':u_form,'p_form':p_form,'myorders':myorders}

    return render(request,'cart/profile.html',context)



@login_required
def add_to_cart(request,pk):
    user_profile = get_object_or_404(User,username=request.user.username)
    product = Product.objects.filter(pk=pk).first()
    order_item,status = Orderitem.objects.get_or_create(customer=user_profile,product=product,is_ordered=False)
    user_order = Order.objects.filter(customer=user_profile,is_ordered=False)
    if user_order.exists():
        order = user_order[0]
        if order.items.filter(product = product).exists():
            order_item.quantity+=1
            order_item.save()
            messages.info(request,"This product quantity was updated")
            return redirect(reverse('mycart'))
        else:
            order.items.add(order_item)
            messages.info(request,"Item added to cart")
            return redirect(reverse('mycart'))
    else:
        order=Order.objects.create(customer=user_profile)
        order.items.add(order_item)
        messages.info(request,"Item added to cart")
        return redirect(reverse('mycart'))

@login_required
def remove_from_cart(request,pk):
    product = Product.objects.filter(pk=pk).first()
    user_profile = get_object_or_404(User,username=request.user.username)
    order_item,status = Orderitem.objects.get_or_create(product=product,customer=user_profile,is_ordered=False)
    order_item.delete()
    messages.info(request,'Item has been removed')
    return redirect(reverse('mycart'))

@login_required
def removesingle(request,pk):
    user_profile = get_object_or_404(User,username=request.user.username)
    product = Product.objects.filter(pk=pk).first()
    user_order = Order.objects.filter(customer=user_profile,is_ordered=False)
    if user_order.exists():
        order = user_order[0]
        if order.items.filter(product=product).exists():
            order_item,status=Orderitem.objects.get_or_create(product=product,customer=user_profile,is_ordered=False)
            if order_item.quantity>1:
                order_item.quantity-=1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request,"Item quantity updated")
            return redirect('mycart')
        else:
            messages.info(request,"This item was not in your cart")
            return redirect('mycart')
    else:
        messages.info(request,"You do not have active order")
        return redirect('mycart')

def get_user_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(User, username=request.user.username)
    order = Order.objects.filter(customer=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0

@login_required

project/cart/templates/cart/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link href="https://fonts.googleapis.com/css?family=Calistoga&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Carter+One|Fugaz+One|Luckiest+Guy|Monoton&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Alatsi&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Changa+One|Righteous&display=swap" rel="stylesheet">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   <style >
   h1{
     color:darkblue;
text-shadow: 1px 1px #ffffff  ;
font-family: 'Calistoga';
font-size:50px;
   }
   h3{
     color:darkblue;
font-family: 'Alatsi', sans-serif;
font-size:30px;

   }
   h4{
     color: #fcfcfc;

   }
   .jumbotron{
     background:rgba(212, 230, 255, 0.9)

   }


   </style>
  </head>
  <body  class=""style="background-image: url('{% static "p.jpg"%}');background-size:cover;background-attachment: fluid;">
    <nav class=" navbar fixed-top navbar-expand-lg " style="background-color:#1e00ff;margin:5px;border-radius:20px;padding-top:1px;padding-bottom:2px">
      <div class="container-fluid">


      <a class="navbar-brand" style="font-size:60px;font-family: 'Changa One', cursive;color:white;" href="{% url 'productlist' %}">EASY WAY</a>


      <button class="navbar-toggler " style="background:white;;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar" style="color:darkblue;">l</span>
                        <span class="icon-bar"  style="color:darkblue">l</span>
                        <span class="icon-bar" style="color:darkblue">l</span>


</button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">

 <div class="navbar-nav mr-auto" >
        <a class="nav-item nav-link "style="font-size:30px;font-family: 'Calistoga', cursive;color:white;margin-top:15px" href="{% url 'categorylist' %}">CATEGORIES</a>

</div>


  <div class="navbar-nav ml-auto " >
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" style="font-size:30px;font-family: 'Calistoga', cursive;margin-top:20px;color:white;" href="{% url 'mycart' %}">MY CART</a>

        <a class="nav-item nav-link"  href="{%url 'profile'%}"><img  style="border-radius:50%;height:75px;width:100px"src="{{ request.user.profile.image.url }}" ></a>

        {% else %}
        <a class="nav-item nav-link" style="font-size:30px;font-family: 'Calistoga', cursive;color:white;" href="{% url 'login' %}">LOGIN</a>
        <a class="nav-item nav-link" style="font-size:30px;font-family: 'Calistoga', cursive;color:white;" href="{% url 'register' %}">REGISTER</a>
        {% endif %}
</div>

</div>

    </div>

    </nav>



<div class="container" >

  <div style="margin-top:120px">
    {% if messages %}
       {% for message in messages %}
       <div class="alert alert-{{message.tags}}">{{ message }}

       </div>
       {% endfor %}
    {% endif %}
  </div>
</div>

<div class="container" style="margin-top:150">

    {% block content %}


    {% endblock %}
  </div>

  </body>
</html>

project/cart/templates/cart/category_detail.html
{% extends "cart/base.html" %}
{% block content %}
<div class="jumbotron" >
  <h1>{{ object.name }}</h1>
  {% if request.user.is_superuser %}
  <a class="btn btn-warning" href="{% url 'categoryupdate' object.id %}">UPDATE</a>

  <a class="btn btn-danger" href="{% url 'categorydelete' object.id %}">DELETE</a>
{% endif %}


</div>
<div class="container">

<div class="jumbotron" style="background:transparent">
  <div class="row" class="mx-auto d-block img-fluid unlock-icon">

  {% for product in object.product_set.all %}

  <div class="card text-center col-lg-3 col-xs-6 " style="border-radius:2%;margin:20px;padding-left:40px">

  <img class="card-img-top" style="width:100%;height:300px"src="{{ product.image.url }}" alt="">
  <div class="card-body">
 <a href="{% url 'productdetail' product.id %}"><h2 style="color:black" class="card-title">{{ product.title }}</h2></a>
 <h2 class="card-text" style="color:red">Rs {{ product.price }}</h2>
</div>
</div>

{% endfor %}
</div>
</div>
</div>


  {% endblock %}

project/cart/templates/cart/category_list.html
{% extends "cart/base.html" %}

{% block content %}
<div class="jumbotron">

<h1>CATEGORIES</h1>
{% if request.user.is_superuser %}
<button type="submit" class="btn btn-primary" ><a  style="color:white"href="{% url 'categorycreate' %}">CREATE CATEGORY</a></button>
<button type="submit" class="btn btn-primary" ><a  style="color:white"href="{% url 'productcreate' %}">CREATE PRODUCT</a></button>
{% endif %}
<p></p>
<table class="table  table-hover ">

{% for i in object_list %}
  <tr class="table-active">
  <td style="color:black;"><a  style="color:white;" href="{% url 'categorydetail' i.id %}">{{ i.name }}</a></td>
  </tr>
  {% endfor %}
</table>
</div>

{% endblock %}

project/cart/templates/cart/login.html
{% extends "cart/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

  <div class="jumbotron" >
    <h1>LOGIN NOW</h1>
    <p></p>
    <form  method="post">
      {% csrf_token %}
        {{ form|crispy }}
        <button type="sumbit" class="btn btn-primary">LOGIN </button>
        <p></p>

    </form>


  </div>

{% endblock %}

project/cart/templates/cart/order_confirm_delete.html
{% extends "cart/base.html" %}
{% block content %}
<form method="POST" >
  {% csrf_token %}
    <h1 style="color:white">Are you sure you want to delete "{{ object.customer }}"?</h1>
    <button class="btn btn-danger"  type="submit" name="button">DELETE</button>
</form>
{% endblock%}

project/cart/templates/cart/orderitem_confirm_delete.html
{% extends "cart/base.html" %}
{% block content %}
<form method="POST" >
  {% csrf_token %}
    <h1 style="color:white">Are you sure you want to delete "{{ object }}"?</h1>
    <button class="btn btn-danger"  type="submit" name="button">DELETE</button>
</form>
{% endblock%}

project/cart/templates/cart/orderitem_detail.html
{% extends "cart/base.html" %}

{% block content %}

<div class="jumbotron">
  <h1>{{object.customer}}</h1>
  <p>

  </p>
  <h2>PRODUCT : {{object.product.title }}</h2>
  <p>

  </p>
  <h2>ORDERED : {{object.is_ordered }}</h2>
  <p>

  </p>
  <h2>QUANTITY : {{ object.quantity }}</h2>

  <a class="btn btn-warning" href="{% url 'orderitemupdate' object.id %}">UPDATE</a>

  <a class="btn btn-danger" href="{% url 'orderitemdelete' object.id %}">DELETE</a>

  </div>

{% endblock %}

project/cart/templates/cart/payment.html
{% extends "cart/base.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="jumbotron">
<h1>PAYMENT</h1>
<form >
{% csrf_token %}
{{ form|crispy}}
<a class="btn btn-primary" href="{% url 'updateprofile'%}">ORDER</a>

</form>



</div>

{% endblock %}

project/cart/templates/cart/proceedtobuy.html
{% extends "cart/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="jumbotron">

<h1>Select a delivery address</h1>
<form  >
  {% csrf_token %}
  {{form|crispy}}

  <a class="btn btn-primary"href="{% url 'payment' %}">CONTINUE</a>
</form>
</div>
{% endblock %}

project/cart/templates/cart/product_confirm_delete.html
{% extends "cart/base.html" %}
{% block content %}
<form method="POST" >
  {% csrf_token %}
    <h1 style="color:white">Are you sure you want to delete "{{ object.title }}"?</h1>
    <button class="btn btn-danger"  type="submit" name="button">DELETE</button>
</form>
{% endblock%}

project/cart/templates/cart/product_list.html
{% extends "cart/base.html" %}

{% block content %}
<div class="jumbotron">
  <h1>PRODUCTS</h1>

</div>

<div class="jumbotron" style="background:transparent">
  <div class="row" class="mx-auto d-block img-fluid unlock-icon">
  {% for product in object_list %}
  <div class="card text-center col-lg-3 col-xs-6 " style="border-radius:2%;margin:20px;padding-left:40px">
  <img class="card-img-top" style="width:100%;height:300px"src="{{ product.image.url }}" alt="">
  <div class="card-body">
    <a href="{% url 'productdetail' product.id %}"><h2 style="color:black" class="card-title">{{ product.title }}</h2></a>

    <h2 class="card-text" style="color:red">Rs {{ product.price }}</h2>
</div>
</div>
{% endfor %}

</div>

</div>

  {% endblock %}

project/cart/templates/cart/register.html
{% extends "cart/base.html" %}

{% load crispy_forms_tags %}
{% block content %}

  <div class="jumbotron" >
    <h1>REGISTER NOW</h1>
    <p></p>
    <form  method="post">
      {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">REGISTER</button>
        <p></p>
        <h3>Already have an account? <a href="#">Sign In</a></h3>
    </form>


  </div>

{% endblock %}

project/cart/templates/cart/user_list.html
{% extends "cart/base.html" %}
{% block content %}
<div class="jumbotron">

 <h1>USERS</h1>
 <p>

 </p>
 {% if object_list.exists%}

 <table class="table  table-hover table-dark">
   <thead class="bg-danger">

     <tr>
       <th><h2>USERNAME</h2></th>
       <th><h2>EMAIL</h2></th>
       <th></th>
       <th></th>

     </tr>

   </thead>
{% endif%}
 {% for user in object_list %}

 <tr>
   <td><h3><a href="{% url 'userdetail' user.id %}">{{ user.username }}</a></h3></td>
   <td><h4>{{ user.email }}</h4></td>



 </tr>
 <tr>
     <td>
       {% empty %}
      <h1>NO USERS</h1>
     </td>
</tr>
{% endfor %}
</table>

</div>


{% endblock %}